name: ctracker
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.05.30
  - certifi=2020.6.20
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - pip=19.3.1
  - python=2.7.18
  - readline=8.2
  - setuptools=44.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.37.1
  - zlib=1.2.13
  - pip:
      - attrs==21.4.0
      - backports-abc==0.5
      - backports-functools-lru-cache==1.6.4
      - bkcharts==0.2
      - bokeh==0.13.0
      - cachetools==3.1.1
      - chardet==4.0.0
      - cloudpickle==0.8.0
      - conda==4.3.16
      - configparser==4.0.2
      - cycler==0.10.0
      - cython==0.29.33
      - dask==1.2.2
      - enum34==1.1.10
      - futures==3.3.0
      - idna==2.10
      - jinja2==2.9.6
      - kiwisolver==1.1.0
      - locket==0.2.0
      - markupsafe==1.1.1
      - matplotlib==2.2.5
      - netcdf4==1.2.4
      - numpy==1.15.4
      - packaging==19.1
      - pandas==0.24.2
      - partd==0.3.8
      - pycosat==0.6.3
      - pyparsing==2.2.0
      - python-dateutil==2.6.1
      - pytz==2023.3
      - pyyaml==3.12
      - requests==2.14.2
      - ruamel-ordereddict==0.4.15
      - ruamel-yaml==0.16.13
      - ruamel-yaml-clib==0.2.2
      - scipy==0.19.1
      - singledispatch==3.7.0
      - six==1.10.0
      - subprocess32==3.5.4
      - toolz==0.10.0
      - tornado==4.5.1
      - xarray==0.9.6
      - xmitgcm==0.2.1
