name: particle-tracking
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - affine=2.3.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=11.0.0
  - asciitree=0.3.3
  - attrs=22.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bokeh=3.2.1
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - cftime=1.6.2
  - charset-normalizer=2.0.4
  - click=8.0.4
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - contourpy=1.0.5
  - curl=8.1.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=0.12.0
  - dask=2023.6.0
  - dask-core=2023.6.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.6.0
  - entrypoints=0.4
  - expat=2.4.9
  - fasteners=0.16.3
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2023.4.0
  - geos=3.8.0
  - geotiff=1.7.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=58.2
  - idna=3.4
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - ipympl=0.8.7
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.2
  - jinja2=3.1.2
  - jpeg=9e
  - json-c=0.16
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kealib=1.4.14
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.1.1
  - libdap4=3.19.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgdal=3.0.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libkml=1.3.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.8.0
  - locket=1.0.0
  - lxml=4.9.1
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - mysql=5.7.24
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - netcdf4=1.6.2
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numcodecs=0.11.0
  - numexpr=2.8.4
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openjpeg=2.4.0
  - openssl=1.1.1v
  - orc=1.7.4
  - packaging=23.0
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.40.0
  - ply=3.11
  - poppler=0.81.0
  - poppler-data=0.4.11
  - proj=6.2.1
  - prometheus_client=0.14.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.17
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-lmdb=1.4.1
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2022.7
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - rasterio=1.2.10
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - scipy=1.11.1
  - send2trash=1.8.0
  - setuptools=68.0.0
  - shapely=2.0.1
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tblib=1.7.0
  - terminado=0.17.1
  - tiledb=2.3.3
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - typing_extensions=4.7.1
  - tzdata=2023c
  - uriparser=0.9.7
  - urllib3=2.0.3
  - utf8proc=2.6.1
  - utm=0.7.0
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.6.0
  - xarray=2023.6.0
  - xerces-c=3.2.4
  - xmitgcm=0.5.2
  - xyzservices=2022.9.0
  - xz=5.4.2
  - yaml=0.2.5
  - zarr=2.13.3
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - asttokens==2.2.1
      - comm==0.1.3
      - executing==1.2.0
      - importlib-metadata==6.5.0
      - ipykernel==6.22.0
      - jedi==0.18.2
      - jupyter-client==8.2.0
      - mitgcmutils==0.1.2
      - platformdirs==3.2.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - pyzmq==25.0.2
      - stack-data==0.6.2
      - traitlets==5.9.0
      - typing-extensions==4.5.0
      - wcwidth==0.2.6
